use f string
hsf-training/hsf-training-matplotlib pull request #138
Opened 2022-10-01 20:14 UTC by Vaibhav-Chopra-GT

fixes(#76)

Added f-strings in print statements, and replaced  `var_name + units` with `f"{var_name}{units}"`.

2022-10-01 20:20 UTC, GuillermoFidalgo commented
This failed the blacken docs check. Question @klieret is Black also not suppose to fix them automatically?

2022-10-01 20:22 UTC, Vaibhav-Chopra-GT commented
I fixed it locally!

2022-10-01 21:05 UTC, amangoel185 approved these changes

2022-10-01 21:17 UTC, amangoel185 requested changes
Hi @Vaibhav-Chopra-GT, could you also fix line 393 and line 466?

2022-10-01 21:47 UTC, amangoel185 approved these changes

2022-10-01 21:48 UTC, klieret approved these changes
I think adding `:,` would be nice but otherwise good work & thank you!

2022-10-01 21:48 UTC, klieret commented on _episodes/04-higgs-search.md
> +    print(f"{s}       Initial events:  {len(branches[s]['m4l'])}")
Let's make this slightly fancier and add `:,` for all long ints that we print, e.g., `{len(branches[s]['m4l']):,}`. It's a great win for readability!

2022-10-01 21:48 UTC, klieret commented on _episodes/04-higgs-search.md
> +    print(f"{s}       Initial events:  {len(branches[s]['m4l'])}")
Same with the after selection below and the stack_...

2022-10-02 14:55 UTC, klieret commented on _episodes/04-higgs-search.md
> +    print(f"{s}       Initial events:  {len(branches[s]['m4l'])}")
@Vaibhav-Chopra-GT

2022-10-03 07:19 UTC, amangoel185 requested changes
@Vaibhav-Chopra-GT, I believe you'd also have to make changes to the outputs, since the outputs would have a `,` for the long integers. For example, the output on line 318 would become something like:

```
data_A       Initial events:  32
data_B       Initial events:  108
data_C       Initial events:  174
data_D       Initial events:  277
mc_345060.ggH125_ZZ4lep       Initial events:  163,316
mc_344235.VBFH125_ZZ4lep       Initial events:  189,542
mc_363490.llll       Initial events:  547,603
mc_361106.Zee       Initial events:  244
mc_361107.Zmumu       Initial events:  148
```

Could you also change the relevant outputs?

2022-10-03 09:34 UTC, amangoel185 approved these changes
Everything looks good now, thank you for your contribution! :)

2022-10-03 09:34 UTC, merged