docs: update CITATION
hsf-training/hsf-training-matplotlib pull request #75
Opened 2022-07-25 17:30 UTC by amangoel185

I have updated the CITATION with information from the Matplotlib Training Presentation. My apologies if I got something wrong. A few more changes need to be made before the CITATION is finalised:

- [ ] Add abstract. We need a one liner for the module.
- [ ] Add ORCID for everyone if available.
- [ ] Add/Remove License. Since `CC BY 4.0` license is used after modification, do we mention `CC BY 4.0` license or nothing at all?

2022-07-25 17:41 UTC, klieret commented
Regarding the license, it's still a CCBY4.0, the modification is only regarding the copyright owners, I think

2022-10-01 19:16 UTC, GuillermoFidalgo requested changes
Add 0000-0001-8605-9772 as my Orcid Id number.

2022-10-01 19:16 UTC, GuillermoFidalgo commented on CITATION
> +  orcid: "FIXME"
Add 0000-0001-8605-9772 as orcid I'd number.

2022-10-01 19:36 UTC, GuillermoFidalgo approved these changes

2022-10-03 23:06 UTC, klieret approved these changes
LGTM!

2022-10-03 23:07 UTC, klieret requested changes

2022-10-03 23:07 UTC, klieret commented on CITATION
> +abstract: "FIXME"
Still one fixme here though. Just copy paste the thing from the index

2022-10-05 19:57 UTC, amorenobr commented
My Orcid ID number is 0000-0001-8415-2543

2022-10-05 22:29 UTC, klieret approved these changes
Thanks a lot!

2022-10-06 03:14 UTC, Marchela04 commented
Thank you @amangoel185 
I didn't have an id, but I created one
https://orcid.org/0000-0003-2393-3367

2022-10-06 10:37 UTC, merged